audit_header: false
title: Campbell &amp; Kellar Team Real Estate Video Blog
description: If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Campbell &amp; Kellar Team - your professional Baltimore &amp; Carroll Counties Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Nick Kellar
  license_number:
  about_markdown: |
    Campbell &amp; Kellar Team of Kellar Williams Legacy is a fast growing, progressive Real Estate team pioneering evolution of our industry and kicking a dent in the Baltimore metro community and local real estate market.  Our approach is Family Helping Families be strategic in making decisions with clear direction while supporting with strong leadership, communication, expectations, and accountability.

    We use progressive systems &amp; tactics, strategic thinking, and years of experience to help position our clients to have the right information so that they can ultimately make the right decisions.
  market: Baltimore &amp; Carroll Counties
  brand: Campbell &amp; Kellar Team
  brokerage: Keller Williams Legacy
  address: 1515 Reisterstown Road, 2nd floor<br>Pikesville, MD 21208
  phone: 443-660-9229
  phone2: 443-964-1000
  email: Nick@theCKteam.com
  url: http://www.CampbellandKellarTeam.com
  first_CTA_text: Home Evaluation
  first_CTA_URL: http://www.bestmdhomesearch.com/homevalue/value/?src=vyral
  second_CTA_text: Home Search
  second_CTA_URL: http://www.bestmdhomesearch.com/?src=vyral
  VR_form: http://oi.vresp.com?fid=b75e53759f
welcome_headline: Get Educated About Real Estate
welcome_text_markdown: |
  Our mission at The Campbell &amp; Kellar Team is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/theCKteam/
  linkedin_url: https://www.linkedin.com/in/nick-kellar-b3a33112
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCtNQYKYMqRRtJVLwGppVZPA
  twitter_url: https://twitter.com/theckteamnick
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/CKteam/
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/campbell-kellar-team-real/id1173621484?mt=2
podcast:
  title: Campbell &amp; Kellar Team Real Estate Podcast
  categories: News &amp; Politics
  image: /img/Kellar_podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Baltimore &amp; Carroll Counties Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Campbell &amp; Kellar Team - your professional Baltimore &amp; Carroll Counties Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Baltimore &amp; Carroll Counties, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Nick Kellar
images:
  client_headshot_path: '/img/headshot.jpg'
  hero_logo_path: '/img/logo.png'
  hero_text: Real Estate Video Blog
  hero_background_hex: '#fff'
  hero_image_path: '/img/background.jpg'
brand_color: '#008AAC'
theme_color: '#000'
theme_text_color: '#fff'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
